### ISSUE TITLE
Do you plan to do "OutputStream"?

### ISSUE THREAD

**Issue by kelvinjm** [stbuehler/xz-jni#1]
Do you plan to extend the functionality about making archives? A decompression is fine, but the compression would be a great performance benefit (compression is slower after all).

Thanks

**Comment by stbuehler** [comment]
Hi!

I think compression has a much simpler interface:
- either pass the whole data to be compressed at once
- stream the data through a context

But there is no seeking involved, which was the main reason I wrote this library.

Given I don't need the feature I don't have any plans working on it.
